### ISSUE TITLE
Cannot get source files

### ISSUE THREAD

**Issue by el-guero-mero** [maitrey-shroff/imgMark#1]
Hello Maitrey,

I cannot seem to get any files out of this repo. All I get is the README file and the /imgMARK folder, but no contents inside the folder.

**Comment by maitrey-shroff** [comment]
Mateo,

Please take a look now, I think I have resolved the issues now.

Apologies for the confusion, and thank you for understanding. 

Have a great weekend!

Maitrey Shroff
maitrey.shroff@gmail.com | 408.439.2289

**Comment by el-guero-mero** [comment]
Wonderful, thank you! I'll take a look.
